### ISSUE TITLE
Grid depth bug

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit-web#29] opened 2019-09-05 21:11 UTC
The grid in `app.html` is displaying over loaded sites, even though their positioned above the grid.

### Screenshots
![depthCapture](https://user-images.githubusercontent.com/29695350/64380899-9d091280-cff7-11e9-8f27-a240188d449b.PNG)
![tcsitesCapture](https://user-images.githubusercontent.com/29695350/64380900-9d091280-cff7-11e9-96e9-fe766f7a009e.PNG)

**Comment by modulesio** [comment] 2019-09-05 21:12
Looks like there is some clipping though right? So the depth buffer works but isn't matching?

**Comment by chrisplatorres** [comment] 2019-09-05 21:14
Yes there is clipping, maybe it is due to the transparency of the grid:

![apaintexowebgif7](https://user-images.githubusercontent.com/29695350/64381129-186ac400-cff8-11e9-987c-49cab27dc5a3.gif)

**Comment by chrisplatorres** [comment] 2019-09-05 21:15
it might be the grid's transparency and in the OP, the world was actually *under* the grid.

**Comment by modulesio** [comment] 2019-09-05 21:17
That could be because our top-level THREE scene isn't using the same XR camera parameters.

How do different child RT sites interact with each other?

**Comment by modulesio** [comment] 2019-09-05 21:26
Might be fixed by https://github.com/exokitxr/exokit-web/pull/30/files.

**Comment by modulesio** [comment] 2019-09-05 21:32
Hm, I see, every site can set its own `depthNear`/`depthFar`. This applies to both WebVR and WebXR.

We'll need to check each particular case of this bug and https://github.com/exokitxr/exokit-web/pull/30 is probably insufficient.

**Comment by modulesio** [comment] 2019-09-08 07:34
As far as I can tell this works fine now. Is there still a reproduction case?

**Comment by modulesio** [comment] 2019-09-09 18:34
Wasn't able to reproduce this recently, so closing.

**Closed by modulesio** 2019-09-09 18:34 UTC
Labels: bug
